### PR TITLE
Add the ability to use RabbitMQ transactions

### PR DESCRIPTION
**Pull request by lightster**
Use RabbitMQ transactions in superqueuer

Issue #9

### CODE REVIEW

**Comment by lightster** [comment]
@Twenty7 I haven't thoroughly tested these RabbitMQ transaction changes, but can you take a peek and let me know if I am going down a completely wrong path?

**Comment by Twenty7** [comment]
The transactions within Hodor/MessageQueue/Queue.php are just to manage the batches, it doesn't start a transaction like a database transaction, correct?

**Comment by lightster** [comment]
@Twenty7 That's correct. Perhaps I should re-think the name.

Also, I think I want to change the way the batches in the superqueuer work. Rather than doing potentially thousands of jobs, I should probably make sure the batches don't grow over a few hundred.

**Comment by Twenty7** [comment]
I think the name is okay, I just wanted to make sure.  Though it wouldn't hurt to change the name.   Yes, limiting the batch size would be good.

**Comment by lightster** [comment]
Welp. I accidentally merged this. I messed up my local master branch, unknowingly recreated it from the push_transactions branch, and then pushed the new master branch :cry: It was mostly ready to go, so I am not going to go through the trouble to revert it. I'll change the names and limit the batch size in other pull requests.

**Pull request merged**
